print("Hello.\n")
print("You are about to take a journey. \nSomewhere, right now, a dog is about to complete their time on this side of the grey veil. \nThat seperates us from this world... to the next. \nSee if you can't reach out to our friend. \nFeel yourself joining your spirit with this dog, see the world... through their eyes.... \n")
dog_name = input('Are you connected? Maybe you can tell me their name to make sure?:  ')
print()
print(dog_name, "? Really.... That's a good name for a .... a.... well.... hmmmm...\n")
print()
dog_breed = input("Reach out again... what kind of breed is our friend?:  ")
print()
print('Ah! Of course! A"',dog_breed,'"A fine breed, with a fine name.',dog_name,'"the"',dog_breed,'.\n')
print("I think you're getting a stronger connection... maybe you feel a little scared, or uncomfortable? \nIt's probably because your friend  is feeling scared too. Try and think of calming thoughts.")
print()
fav_smell = input('Try thinking of a really good smell, don\'t worry if its something a dog might like:  ')
print()
print("I think you found our friend\'s favorite smell, well done,\nIts a good smell...", fav_smell, ".")
print()
fav_food = input('Can you taste that? Our friend is trying to remember their favorite meal. Mmm, it\'s... it\'s:  ')
print()
print("Yes! That\'s it!",fav_food,"! Our friend sure knows what\'s good.")
print()
sec_breed = input('Our scared friend is thinking of a friend, another breed of dog... It\'s a:  ')
print()
print('That\'s right. Our friend\'s best friend, the',sec_breed,'from next door. \nIt\'s good to have friends.')
print()
print('But, you still.... sense that scared feeling, don\'t you? Like something scary is watching you both?')
print()
print('............')
print()
print()
scary_thing = input("What is it? .... I don\'t think I like it .... I think it\'s a... a:  ")
print()
print('A',scary_thing,'....You think so? Maybe it isn\'t. Our friend seems very scared now.')
print('You should try and be with your friend. Close your eyes for a few seconds... when you open them....')
print()
print('You\'ll take the journey together..... through',dog_name,'\'s eyes, but both your spirits.')
print()
print('Are you ready? It\'s starting....')
print()
print()
print()
print()
print("You lay on your side, grasping for breath. Your human is there, crying, you feel very scared, but you also \ndon't want them to be sad.")
print()
choice_1 = ("Whimpering and scared you reach out for your human. They take you paw and nuzzle your face. Somehow you feel a little braver and calmer and their nearby face for some strange reason makes you remember",fav_smell,". The scent overwhelms you and you close your eyes, the next time you open them.")
print()
choice_2 = ("You're scared but you see your human crying and sad. And you don’t want that. You take all your remaining strength and pick your head up to be able to reach their face. Your kisses seem to reassure them and for the oddest moment you taste", fav_food, "and remember the last time your human and you shared that most delicious of foods, content with the memory, you close your eyes, the next time you open them...")
print()
x = input('Do you comfort your human or let them comfort you? Enter 1 for comfort them. 2 for accept their comfort:  ')
if x == 1:
    print(choice_1)
else:
    print(choice_2)
print('You see that you are in a strange but wonderful place. Bright colors and exciting smells. You can almost taste',fav_food,'as you gulp in the air. Young pups run around playing, but seem to not know basic dog things, like how to smell for each other or howl or bark... very strange. You look behind you there is a small tunnel and in it you can see your human in your bedroom, they’re huddled over something and still sad. You want to go back, but your also drawn to this place. As if you belong here, or you will belong here. Before you make up your mind. A presence and voice is suddenly near you. It’s a safe presence and a kind voice. You instinctively trust it. The voice says, "Hello',dog_name,'of the',dog_breed,'clan." And starts to what a good dog you were, and how important you were in your life, and it’s sad, but your human must go on without you. It’s just the way it has to be. But the voice tells you to look one more time. As you do your fur stands up and you growl without thinking, because behind your human is several dark figures. They look like,',scary_thing,'And they are whispering dark and bad sounding words in the ear of your human.')
print()
input('Are you ready to continue the journey? Press Enter:  ')
print()
print('The voice tells you to be calm. Humans and Dogs can’t see the dark ones. Only "Knights of the Order of the First Hound" can see and do battle with such creatures, the voice explains, and that you must now make a choice. More pups are being readied to go Earth. But they need training. Dogs on earth are as important to keep the dark ones at bay as much as the Order of the First Hound are. The voice invites you to stay and teach the young ones all they need to learn to be the best dogs they can be. But you can also choose to go back as a spirit and join the Order of the First Hound and fight against the dark ones. Both choices are good, and both choices are important. Which one do you choose?')
print()
input('Are You ready to continue the journey? Press Enter?:  ')
print()
print('Choosing to stay, the voice senses your decision, “You’ve done a good service on earth.”, says the voice. “The young ones here need you to teach them to stay, to bark, to comfort and bring joy, to wag their tails, and to howl, because howling is a secret language that encourages the Knights of the Order and gives them strength to face the darkness.” You look down and at your paws is the smallest',sec_breed,'you’ve ever seen, feebly moving its tail up, down, and sideways, scenting in the fresh air and seeing the golden sky. You inhale deeply before giving your new pup its first lesson on how to be a proper dog.')